//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Contract_Receivables
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<decimal> AmountCollected { get; set; }
        public Nullable<decimal> NewAmountCollected { get; set; }
        public string DateOfReceipt { get; set; }
        public string TicketOpeningAndDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string Status { get; set; }
    }
}
