//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ContractDeliveryHistory
    {
        public int ID { get; set; }
        public int ProductDetailID { get; set; }
        public int ContractID { get; set; }
        public Nullable<decimal> NewDeliveryEDCount { get; set; }
        public string DeliveryDate { get; set; }
        public string DeliveryedBy { get; set; }
        public string CreatedTime { get; set; }
    }
}
