//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ContractProductDetail
    {
        public int ID { get; set; }
        public int ContractID { get; set; }
        public string ProductName { get; set; }
        public string Customer_ProductName { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public string ifDrive { get; set; }
        public string ProductSpec { get; set; }
        public string P_Speed { get; set; }
        public string P_CarryingCapacity { get; set; }
        public string P_ElectricalRequirements { get; set; }
        public string P_EquipmentWorkplace { get; set; }
        public string P_Main_materialofworkpiece { get; set; }
        public string P_ChildPartSpecRange { get; set; }
        public string P_ChildPartWeight { get; set; }
        public string P_WorkpieceFeedingMode { get; set; }
        public string P_RollerDiameter { get; set; }
        public string P_RollerMaterial { get; set; }
        public string P_RollerSurface { get; set; }
        public string P_RollerTransferMode { get; set; }
        public string P_MainBeaMaterial { get; set; }
        public string Units { get; set; }
        public string Count { get; set; }
        public Nullable<System.DateTime> DueDay { get; set; }
        public string DeliveryedCount { get; set; }
        public string NewDeliveryedCount { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string InstalledQuantity { get; set; }
        public string newInstalledQuantity { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Acceptance { get; set; }
        public Nullable<System.DateTime> AcceptanceDate { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string Status { get; set; }
        public string Price { get; set; }
    }
}
