//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee__dele
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public int CCID { get; set; }
        public string fingerprint { get; set; }
        public string EmployeeName { get; set; }
        public string PWD { get; set; }
        public string Shift { get; set; }
        public Nullable<System.DateTime> EmploymentDate { get; set; }
        public string LeaveDate { get; set; }
        public string DepartMent { get; set; }
        public string Manager { get; set; }
        public Nullable<int> auth { get; set; }
        public string StatusID { get; set; }
        public string Tel { get; set; }
        public string IDCard { get; set; }
    }
}
