//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_Accounting_Vouchertwo
    {
        public int 编号 { get; set; }
        public string 摘要 { get; set; }
        public string 科目名称 { get; set; }
        public Nullable<decimal> 借方 { get; set; }
        public Nullable<decimal> 贷方 { get; set; }
        public string 状态 { get; set; }
        public string 借贷方向 { get; set; }
        public Nullable<decimal> 金额 { get; set; }
        public string 凭证单号 { get; set; }
        public Nullable<int> 序号 { get; set; }
        public Nullable<int> 报销单ID { get; set; }
        public Nullable<int> 部门ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<int> PzID { get; set; }
    }
}
