//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_CostSetup
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public string Unit { get; set; }
        public Nullable<int> CostTypeID { get; set; }
        public string CostPercent { get; set; }
        public string Status { get; set; }
    }
}
