//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_Caption_of_Account
    {
        public int 编号 { get; set; }
        public string 科目代码 { get; set; }
        public string 科目名称 { get; set; }
        public string 助记码 { get; set; }
        public string 科目类别 { get; set; }
        public string 余额方向 { get; set; }
        public string 全名 { get; set; }
        public string 现金科目 { get; set; }
        public string 银行科目 { get; set; }
        public string 项目辅助核算 { get; set; }
        public string 状态 { get; set; }
    }
}
