//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FI_Voucher_Flow_Setup
    {
        public int ID { get; set; }
        public string 凭证类型 { get; set; }
        public string 一级审核 { get; set; }
        public string 二级审核 { get; set; }
        public string 三级审核 { get; set; }
        public string 四级审核 { get; set; }
        public string 五级审核 { get; set; }
        public string 六级审核 { get; set; }
        public string 七级审核 { get; set; }
        public string 八级审核 { get; set; }
        public string 凭证状态 { get; set; }
    }
}
