//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public int ID { get; set; }
        public string ContractNumber { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<int> InMakeQTY { get; set; }
        public string PartNumber { get; set; }
        public string PartSpec { get; set; }
        public string PartMaterial { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> Money { get; set; }
        public Nullable<int> ActPurchaseQTY { get; set; }
        public string Units { get; set; }
        public string MakeCreatedBy { get; set; }
    }
}
