//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_ApplierList_temp
    {
        public int ID { get; set; }
        public string ApplierCode { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string CategoryID { get; set; }
        public string AdvantageID { get; set; }
        public string LevelID { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string Status { get; set; }
        public string Bank { get; set; }
        public string Account { get; set; }
        public string Representative { get; set; }
        public string Principal { get; set; }
    }
}
