//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Bonusratio
    {
        public int ID { get; set; }
        public string 部门 { get; set; }
        public Nullable<int> 分数 { get; set; }
        public Nullable<int> 奖金 { get; set; }
        public Nullable<double> 比例 { get; set; }
    }
}
