//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_BOM_Design
    {
        public int ID { get; set; }
        public int PartID { get; set; }
        public int ChildPartID { get; set; }
        public Nullable<int> ChildPartQTY { get; set; }
        public Nullable<int> MaterialQTY { get; set; }
        public string MaterialUnits { get; set; }
        public Nullable<int> IsUnit { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedTime { get; set; }
        public string StatusID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Type { get; set; }
        public string MaterialSpec { get; set; }
        public string MaterialName { get; set; }
        public string WhetherToUpload { get; set; }
    }
}
