//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Forum_Comments
    {
        public int id { get; set; }
        public string Comments { get; set; }
        public string CommentsPicture { get; set; }
        public int ForunID { get; set; }
        public System.DateTime CommentsTime { get; set; }
        public int EmployeeID { get; set; }
        public string Status { get; set; }
    }
}
