//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Forum
    {
        public int id { get; set; }
        public string Substance { get; set; }
        public string Avatar { get; set; }
        public string Picture { get; set; }
        public string Title { get; set; }
        public string Columns { get; set; }
        public System.DateTime PostingTime { get; set; }
        public string Status { get; set; }
        public int Record { get; set; }
        public string Collection { get; set; }
        public string CollectionPeople { get; set; }
        public int EmployeeID { get; set; }
        public int Answer { get; set; }
    }
}
