//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Material
    {
        public int ID { get; set; }
        public Nullable<int> Category1ID { get; set; }
        public Nullable<int> Category2ID { get; set; }
        public Nullable<int> Category3ID { get; set; }
        public Nullable<int> ApplierProductTypeID { get; set; }
        public string figureNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartSpec { get; set; }
        public string PartMaterial { get; set; }
        public Nullable<int> StockPCS { get; set; }
        public Nullable<int> StockQTY { get; set; }
        public string Units { get; set; }
        public string ListType { get; set; }
        public Nullable<int> IsUnit { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedTime { get; set; }
        public string Status { get; set; }
    }
}
