//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PartSetting_temp
    {
        public int ID { get; set; }
        public string PartLevel { get; set; }
        public string FigureNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartSpec { get; set; }
        public string PartMaterial { get; set; }
        public Nullable<int> QTY { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsUnit { get; set; }
        public string ListType { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string Note { get; set; }
        public string type { get; set; }
        public string DesignType { get; set; }
        public Nullable<int> MatertID { get; set; }
        public string WhetherToUpload { get; set; }
    }
}
