//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Package
    {
        public int ID { get; set; }
        public string PackageName { get; set; }
        public Nullable<int> WOID { get; set; }
        public Nullable<int> QTY { get; set; }
        public string Units { get; set; }
        public Nullable<int> ShipNoticeID { get; set; }
        public Nullable<int> ShipNoticeDetailID { get; set; }
        public Nullable<int> Checked { get; set; }
        public string CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string StatusID { get; set; }
        public string Note { get; set; }
        public Nullable<int> MaterialId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string ContractNumber { get; set; }
        public string Status { get; set; }
    }
}
