//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PullingListHistory
    {
        public int ID { get; set; }
        public Nullable<int> PullinglistID { get; set; }
        public string FigureNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartMaterial { get; set; }
        public string PartSpec { get; set; }
        public Nullable<int> RequirementPCS { get; set; }
        public Nullable<int> RecievedPCS { get; set; }
        public Nullable<int> QTYofPCS { get; set; }
        public Nullable<int> RequirementQTY { get; set; }
        public Nullable<int> RecievedQTY { get; set; }
        public string Units { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public string CreatedTime { get; set; }
        public string CreatedBy { get; set; }
        public string Status { get; set; }
    }
}
