//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_PurchaseMaterialList
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<int> QTYofPCS { get; set; }
        public Nullable<int> ApplyPurchasePCS { get; set; }
        public Nullable<int> ApplyPurchaseQTY { get; set; }
        public Nullable<int> ActPurchasePCS { get; set; }
        public Nullable<int> ActPurchaseQTY { get; set; }
        public string Units { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> POID { get; set; }
        public string Note { get; set; }
        public string ListType { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string Spec { get; set; }
    }
}
