//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Scanrecord
    {
        public int id { get; set; }
        public string figureNumber { get; set; }
        public string PartNumber { get; set; }
        public string PartSpec { get; set; }
        public string PartMaterial { get; set; }
        public Nullable<int> IQC_Result { get; set; }
        public Nullable<int> IQCPassQTY { get; set; }
        public Nullable<int> PutonPCS { get; set; }
        public Nullable<int> OutPCS { get; set; }
        public Nullable<int> StockPCS { get; set; }
        public string operation { get; set; }
        public string Employee { get; set; }
        public Nullable<System.DateTime> scantrim { get; set; }
    }
}
