//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Task
    {
        public int TaskID { get; set; }
        public Nullable<int> ParentTaskID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ProductDetailID { get; set; }
        public string PriorityCode { get; set; }
        public Nullable<int> TaskLevel { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public string ProductName { get; set; }
        public string ProductSpec { get; set; }
        public string Owner { get; set; }
        public Nullable<int> TaskScore { get; set; }
        public string DueDay { get; set; }
        public string TaskDesc { get; set; }
        public string TaskFile1 { get; set; }
        public string TaskFile2 { get; set; }
        public string TaskFile3 { get; set; }
        public string MachineDesignOwner { get; set; }
        public Nullable<double> MachineDesignBaseTime { get; set; }
        public string MachineDesignConfirm { get; set; }
        public string MachineDesignConfirmTime { get; set; }
        public string MachineDesignifCompleted { get; set; }
        public string MachineDesignCompletedTime { get; set; }
        public Nullable<double> MachineDesignBaseScore { get; set; }
        public Nullable<double> MachineDesignScore { get; set; }
        public string MachineDesignFileName1 { get; set; }
        public string MachineDesignFileName2 { get; set; }
        public string electricalOwner { get; set; }
        public Nullable<double> electricalDesignBaseTime { get; set; }
        public string electricalDesignConfirm { get; set; }
        public string electricalDesignConfirmTime { get; set; }
        public string electricalDesignifCompleted { get; set; }
        public string electricalDesignCompletedTime { get; set; }
        public Nullable<double> electricalDesignBaseScore { get; set; }
        public Nullable<double> electricalDesignScore { get; set; }
        public string electricalDesignFileName1 { get; set; }
        public string electricalDesignFileName2 { get; set; }
        public string QualifiedOwner { get; set; }
        public Nullable<double> QualifiedBaseTime { get; set; }
        public string QualifiedConfirm { get; set; }
        public string QualifiedConfirmTime { get; set; }
        public string QualifiedifCompleted { get; set; }
        public string QualifiedCompletedTime { get; set; }
        public Nullable<double> QualifiedBaseScore { get; set; }
        public Nullable<double> QualifiedScore { get; set; }
        public string SuggestedPoints { get; set; }
        public string IssueOwner { get; set; }
        public Nullable<double> IssueBaseTime { get; set; }
        public string IssueConfirm { get; set; }
        public string IssueConfirmTime { get; set; }
        public string IssueifCompleted { get; set; }
        public string IssueCompletedTime { get; set; }
        public Nullable<double> IssueBaseScore { get; set; }
        public Nullable<double> IssueScore { get; set; }
        public Nullable<double> LastTaskTotalScore { get; set; }
        public string Status { get; set; }
        public string ProductFileName1 { get; set; }
        public string ProductFileName2 { get; set; }
        public string ProductFileName3 { get; set; }
        public string ProductFileName4 { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IfOverdue { get; set; }
        public string P_Speed { get; set; }
        public string P_CarryingCapacity { get; set; }
        public string P_ElectricalRequirements { get; set; }
        public string P_EquipmentWorkplace { get; set; }
        public string P_Main_materialofworkpiece { get; set; }
        public string P_ChildPartSpecRange { get; set; }
        public string P_ChildPartWeight { get; set; }
        public string P_WorkpieceFeedingMode { get; set; }
        public string P_RollerDiameter { get; set; }
        public string P_RollerMaterial { get; set; }
        public string P_RollerSurface { get; set; }
        public string P_RollerTransferMode { get; set; }
        public string P_MainBeaMaterial { get; set; }
        public string ifDrive { get; set; }
        public string MachineDesignOverDue { get; set; }
        public string ElectricalDesignOverDue { get; set; }
        public string QualifiedOverDue { get; set; }
        public string IssueOverDue { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedTime { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<double> PCS { get; set; }
        public string Units { get; set; }
        public string PEOwner { get; set; }
        public string PEBaseTime { get; set; }
        public string PEConfirm { get; set; }
        public string PEConfirmTime { get; set; }
        public string PEifCompleted { get; set; }
        public string PECompletedTime { get; set; }
        public string PEOverDue { get; set; }
        public string PMCOwner { get; set; }
        public string PMCBaseTime { get; set; }
        public string PMCConfirm { get; set; }
        public string PMCConfirmTime { get; set; }
        public string PMCifCompleted { get; set; }
        public string PMCCompletedTime { get; set; }
        public string PMCOverDue { get; set; }
        public string PurchaseOwner { get; set; }
        public string PurchaseBaseTime { get; set; }
        public string PurchaseConfirm { get; set; }
        public string PurchaseConfirmTime { get; set; }
        public string PurchaseifCompleted { get; set; }
        public string PurchaseCompletedTime { get; set; }
        public string PurchaseOverDue { get; set; }
        public string ProductOwner { get; set; }
        public string ProductBaseTime { get; set; }
        public string ProductConfirm { get; set; }
        public string ProductConfirmTime { get; set; }
        public string ProductIfPutInto { get; set; }
        public string ProductIfPutIntoTime { get; set; }
        public string ProductIfCompleted { get; set; }
        public string ProductCompletedTime { get; set; }
        public string ProductOverDue { get; set; }
        public string WHOwner { get; set; }
        public string WHDeliveryBasetime { get; set; }
        public string WHifConfirm { get; set; }
        public string WHConfirmTime { get; set; }
        public string WHifCompleted { get; set; }
        public string WHCompletedTime { get; set; }
        public string WHOverDue { get; set; }
        public string InstallOwner { get; set; }
        public string InstallBasetime { get; set; }
        public string InstallifConfirm { get; set; }
        public string InstallConfirmTime { get; set; }
        public string InstallifCompleted { get; set; }
        public string InstallCompletedTime { get; set; }
        public string InstallOverDue { get; set; }
        public string BreakUp { get; set; }
        public string BracketFoot { get; set; }
    }
}
