//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_Task_History_Status
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string WorkContent { get; set; }
        public string Owner { get; set; }
        public Nullable<bool> ifConfirmGetTask { get; set; }
        public string StartTime { get; set; }
        public Nullable<bool> ifCompleted { get; set; }
        public string EndTime { get; set; }
        public string AttchedFile1 { get; set; }
        public string AttchedFile2 { get; set; }
        public string AttchedFile3 { get; set; }
        public Nullable<double> BaseTime { get; set; }
        public Nullable<bool> ifOverDue { get; set; }
        public Nullable<double> BaseScore { get; set; }
        public Nullable<double> LastScore { get; set; }
        public string Status { get; set; }
    }
}
