//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_TaskProgress
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> Item { get; set; }
        public string From { get; set; }
        public string TO { get; set; }
        public string Content { get; set; }
        public string CompletionDescription { get; set; }
        public string CreatedBY { get; set; }
        public string CreatedTIme { get; set; }
        public string Status { get; set; }
    }
}
