//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_WorkorderDetail
    {
        public int ID { get; set; }
        public Nullable<int> Sort { get; set; }
        public string WorkorderID { get; set; }
        public string StationTypeID { get; set; }
        public Nullable<int> WorkHoursOfOneSet { get; set; }
        public string WorkHoursUnits { get; set; }
        public string StartWorkTime { get; set; }
        public string EndWorkTime { get; set; }
        public Nullable<double> WorkHours { get; set; }
        public Nullable<int> RecievedQTY { get; set; }
        public Nullable<int> CompletedQTY { get; set; }
        public Nullable<int> FailedQTY { get; set; }
        public Nullable<int> TrasferNextStationQTY { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public string DueData { get; set; }
        public Nullable<int> LineID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    }
}
