//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YLMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_WorkOrder
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string WorkorderNO { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> ParentPartID { get; set; }
        public Nullable<int> TotalPCS { get; set; }
        public Nullable<int> QTYofOneSet { get; set; }
        public Nullable<int> TotalQTY { get; set; }
        public Nullable<int> FailedPCS { get; set; }
        public Nullable<int> RecievedQTY { get; set; }
        public Nullable<int> CompletedQTY { get; set; }
        public Nullable<int> PackageQTY { get; set; }
        public Nullable<int> ifPackCompleted { get; set; }
        public Nullable<int> InWH { get; set; }
        public Nullable<int> ifInWHWO { get; set; }
        public string DueDay { get; set; }
        public string CreateTime { get; set; }
        public string UpdateTime { get; set; }
        public Nullable<int> CreatedEmployeeID { get; set; }
        public string Status { get; set; }
    }
}
